apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifets:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: sdawes437/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*/.ts"
            dest: .
